language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script: 
  - npm install -g @angular/cli

script:
  - ng build --prod

before_deploy:  
  - copy manifest.yml dist\manifest.yml
  - cd dist
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master